source 'https://rubygems.org'

gem 'actionview'
gem 'activerecord', '4.2.5'
gem 'bcrypt'
gem 'data_mapper'
gem 'faker'
gem 'hashie'
gem 'minitest'
gem 'pony'
gem 'rake'
gem 'require_all'
gem 'sass'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-flash'
gem 'slim'
gem 'sprockets'
gem 'thin'
gem 'tilt-jbuilder', '>= 0.4.0', require: 'sinatra/jbuilder'
gem 'uglifier'
gem 'warden'

group :development do
  gem 'pry'
  gem 'shotgun'
  gem 'sqlite3'
  gem 'tux'
end
